.TH tne_remove_header 3 2024-06-16

.SH NAME
tne_remove_header

.SH LIBRARY
.RI "libtne (" -ltne ")"

.SH SYNOPSIS
.B #include <tne.h>
.P
.BI "void tne_remove_header(struct TNEHeaders " "*headers" ", char " "*name" ");"

.SH DESCRIPTION
.RI "Removes a " "tneheader_t" " according to " "*name" " from " "*headers" "."
.P
tneheader_t and struct TNEHeaders are defined as follows:
.P
.in +4n
.EX
struct TNEHeaders {
    tneheader_t *headers;
    uint32_t header_count;
};

typedef struct {
    char *name;
    uint32_t name_len;

    char *value;
    uint32_t value_len;
} tneheader_t;

.SH RETURN VALUE
Returns nothing, guarantees no failure.

.SH SEE ALSO
.BR tne_add_header (3)
