.TH tne_free_request 3 2024-06-14

.SH NAME
tne_free_request

.SH LIBRARY
.RI "libtne (" -ltne ")"

.SH SYNOPSIS
.B #include <tne.h>
.P
.BI "void tne_free_request(tnerequest_t " "request" ");"

.SH DESCRIPTION
.RI "Frees allocated memory blocks of " "request" "."

.SH RETURN VALUE
On success, returns nothing. On failure, will be memory leak.

.SH SEE ALSO
.BR tne_prepare_request (3)
