.TH tne_set_last_error 3 2024-06-14

.SH NAME
tne_set_last_error

.SH LIBRARY
.RI "libtne (" -ltne ")"

.SH SYNOPSIS
.B #include <tne.h>
.P
.BI "void tne_set_last_error(enum TNEErrors " "code" ");"

.SH DESCRIPTION
Sets last error of tne. It should not be used, it is for the library.

.SH RETURN VALUE
Returns nothing, guarantees no failure.

.SH SEE ALSO
.BR tne_get_last_error (3)
