.TH tne_request 3 2024-06-16

.SH NAME
tne_request

.SH LIBRARY
.RI "libtne (" -ltne ")"

.SH SYNOPSIS
.B #include <tne.h>
.P
.BI "tneresponse_t *tne_request(tnerequest_t " "*request" ");"

.SH DESCRIPTION
.RI "Sends a HTTP 1.1 request using given " "*request" " information and returns a HTTP response in " "tneresponse_t" "."
.P
tneresponse_t and other specifications are defined as follows:
.P
.in +4n
.EX
typedef struct {
    struct TNEHeaders headers;    /* response headers */
    char *data;                   /* response data */
    unsigned long long data_size; /* response data size */
    tnestatus_t status;           /* response status */
} tneresponse_t;

struct TNEHeaders {
    tneheader_t *headers;
    uint32_t header_count;
};

typedef struct {
    char *name;
    uint32_t name_len;

    char *value;
    uint32_t value_len;
} tneheader_t;

typedef struct {
    int code;             /* HTTP status code */
    char *message;        /* returned message of HTTP status code */
    uint32_t message_len;
} tnestatus_t;

.SH RETURN VALUE
.RI "On success, returns " "*tneresponse_t" " filled with returned HTTP response. On failure, returns " "NULL" " and sets last error code."

.SH SEE ALSO
.BR tne_free_request (3)
.BR tne_get_last_error (3)
.BR tne_prepare_request (3)
